# Generated by Django 2.2.7 on 2019-11-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnKrypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystorage',
            name='created_date',
        ),
    ]
